#!/usr/bin/env node
/**
 * freshness-report.js — Report how current the framework mappings are.
 *
 * Reads the freshness block computed by stats.js. Prints, and writes
 * reports/freshness.md.
 *
 * There is no SLA check here because no SLA values exist: docs/FRESHNESS_SLA.md
 * carries TODO(maintainer) slots, and an agent inventing a number would be
 * making a promise about someone else's capacity.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const stats = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'stats.json'), 'utf8'));
const f = stats.freshness;

if (!f) {
  console.error('No freshness block in data/stats.json — run `npm run stats`.');
  process.exit(1);
}

const total = f.checked + f.unchecked;
const lines = [
  '# Framework freshness',
  '',
  '*Generated by `scripts/freshness-report.js`. Do not edit by hand.*',
  '',
  `**${f.current} current · ${f.diverged} diverged · ${f.unchecked} unchecked** ` +
    `(of ${total} frameworks)`,
  '',
  '`unchecked` means nobody has confirmed the upstream version. It is reported',
  'separately from `current` on purpose: not having looked is a different state',
  'from having looked and found no drift.',
  '',
];

if (f.diverged) {
  lines.push('## Diverged — upstream has moved ahead', '',
    '| Framework | Mapped | Upstream | Confirmed |', '|---|---|---|---|',
    ...f.diverged_frameworks.map(
      (d) => `| ${d.name} | ${d.mapped} | **${d.current}** | ${d.checked || '—'} |`),
    '');
}

lines.push(
  '## Coverage of the measurement itself',
  '',
  `${f.checked} of ${total} frameworks have a confirmed upstream version, so freshness`,
  `is genuinely measured for ${f.checked} and unknown for ${f.unchecked}. Populating`,
  '`current_version` in `data/framework-sources.json` is what closes that gap.',
  '',
  'See [docs/FRESHNESS_SLA.md](../docs/FRESHNESS_SLA.md).',
  '',
);

fs.mkdirSync(path.join(ROOT, 'reports'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'reports', 'freshness.md'), lines.join('\n'), 'utf8');

console.log('Written reports/freshness.md');
console.log(`  ${f.current} current · ${f.diverged} diverged · ${f.unchecked} unchecked (of ${total})`);
if (f.diverged) {
  for (const d of f.diverged_frameworks) {
    console.log(`  DIVERGED  ${d.name}: mapped ${d.mapped}, upstream ${d.current}`);
  }
}
