#!/usr/bin/env node
/**
 * validate-aivss.mjs — Check AIVSS vectors against the official specification.
 *
 * AIVSS v0.8 is explicit about its baseline:
 *
 *   "AIVSS requires CVSS v4.0 as its baseline scoring input. Practitioners
 *    should not use CVSS v3.1 scores as inputs to the AIVSS formula, as the
 *    metric structures are not directly comparable."
 *
 * The vectors in agentic-top10/Agentic_AIVSS.md are CVSS **v3.1** shaped, and
 * the file's own references section cites the v3.1 specification. That is not a
 * cosmetic mismatch: v4.0 splits the v3.1 Scope metric into Vulnerable System
 * Impact (VC/VI/VA) and Subsequent System Impact (SC/SI/SA), and the subsequent
 * metrics are the ones that carry agentic propagation — precisely the amplifier
 * these scores exist to express.
 *
 * This reports. It changes no score, because a score is security judgment (C4)
 * and re-deriving 10 AIVSS scores against a different metric structure is SME
 * work, not a text substitution.
 *
 * Output: reports/aivss-violations.md
 * Usage:  node scripts/validate-aivss.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(ROOT, 'reports');
const OUT = path.join(OUT_DIR, 'aivss-violations.md');

const spec = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'aivss-spec.json'), 'utf8'));
const V4_METRICS = spec.cvss4_base_metrics;
const V4_REQUIRED = spec.cvss4_required_metrics;
const V31_ONLY = spec.cvss31_only_metrics;

const SOURCES = ['agentic-top10/Agentic_AIVSS.md'];

const findings = [];
let vectorCount = 0;

for (const rel of SOURCES) {
  const fp = path.join(ROOT, rel);
  if (!fs.existsSync(fp)) continue;
  const lines = fs.readFileSync(fp, 'utf8').split('\n');

  lines.forEach((line, i) => {
    const m = line.match(/AIVSS Vector:\*{0,2}\s*([A-Z]{1,2}:[A-Z](?:\/[A-Z]{1,2}:[A-Z])+)/);
    if (!m) return;
    vectorCount++;
    const vector = m[1];
    const parts = Object.fromEntries(vector.split('/').map((p) => p.split(':')));

    const v31Present = Object.keys(parts).filter((k) => k in V31_ONLY);
    const missing = V4_REQUIRED.filter((k) => !(k in parts));
    const badValue = Object.entries(parts).filter(
      ([k, v]) => V4_METRICS[k] && !V4_METRICS[k].includes(v),
    );

    findings.push({
      file: rel,
      line: i + 1,
      vector,
      isV31: v31Present.length > 0 || missing.includes('VC'),
      v31Present,
      missing,
      badValue,
    });
  });
}

const v31 = findings.filter((f) => f.isV31);
const conformant = findings.filter((f) => !f.isV31 && !f.missing.length && !f.badValue.length);

const out = [
  '# AIVSS vector conformance',
  '',
  '*Generated by `scripts/validate-aivss.mjs`. Reports only — no score is changed.*',
  '',
  `Checked against **${spec.source.title} ${spec.source.version}** ` +
    `([source](${spec.source.url}), accessed ${spec.source.accessed}).`,
  '',
  `**${vectorCount} vector(s) found · ${v31.length} on the wrong baseline · ${conformant.length} conformant**`,
  '',
  '## The requirement',
  '',
  `> ${spec.baseline.quote}`,
  '',
  spec.baseline.note,
  '',
];

if (v31.length) {
  out.push(
    '## Vectors on the CVSS v3.1 baseline',
    '',
    'These use the v3.1 metric structure. Under the AIVSS specification they are',
    'not valid inputs to the formula, so the scores derived from them cannot be',
    'reproduced by a reader following the spec.',
    '',
    '| Line | Vector | Missing v4.0 metrics |',
    '|--:|---|---|',
    ...v31.map((f) => `| ${f.line} | \`${f.vector}\` | ${f.missing.join(', ') || '—'} |`),
    '',
    '**Not fixed here.** Re-deriving a score against a different metric structure is',
    'not a text substitution — VC/VI/VA and SC/SI/SA have no v3.1 equivalent to carry',
    'over, and the subsequent-system impact that distinguishes agentic risk has to be',
    'assessed rather than converted. That is SME work.',
    '',
    'Worksheets with empty value and justification cells are in',
    '[`shared/AIVSS_WORKSHEETS.md`](../shared/AIVSS_WORKSHEETS.md).',
    '',
  );
}

const badValues = findings.filter((f) => f.badValue.length);
if (badValues.length) {
  out.push('## Values outside the metric vocabulary', '',
    '| Line | Vector | Invalid |', '|--:|---|---|',
    ...badValues.map((f) => `| ${f.line} | \`${f.vector}\` | ${f.badValue.map(([k, v]) => `${k}:${v}`).join(', ')} |`),
    '');
}

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT, out.join('\n'), 'utf8');

console.log('Written reports/aivss-violations.md');
console.log(`  ${vectorCount} vector(s) · ${v31.length} on the CVSS v3.1 baseline · ${conformant.length} conformant`);
if (v31.length) {
  console.log(`  AIVSS ${spec.source.version} requires ${spec.baseline.requires}; no score changed (C4).`);
}
